---
##################################################
# Name: pulumi.yaml
# Description: Runs pulumi on environment branches
##################################################

name: Pulumi

on:
  workflow_run:
    workflows:
      - Devenv
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  packages: read
  pull-requests: write
  statuses: write

defaults:
  run:
    shell: bash

env:
  # GitHub
  PROJECT: ${{ github.repository }}
  BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
  BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}

  # Nix
  NIXPKGS_ALLOW_UNFREE: 1

  # Go
  GO111MODULE: on
  GOFLAGS: -mod=readonly

  # Pulumi Secrets
  PULUMI_COMMENT_ON_PR: true
  PULUMI_COMMENT_ON_SUMMARY: true
  PULUMI_ROOT: ./

jobs:
  ##################################################
  # Generate a matrix of possible Pulumi stacks.
  ##################################################

  matrix:
    name: Matrix

    runs-on: ${{ matrix.os }}

    # Only run this job if the devenv workflow was successful.
    if: github.event.workflow_run.conclusion == 'success'

    timeout-minutes: 30
    continue-on-error: false

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - id: generate_matrix
        name: Generating a matrix of Pulumi stack configurations
        # TODO: pulumi stack ls --json | jq -r .[].name
        run: |
          echo "Generating matrix of Pulumi stacks..."
          # yamllint disable-line rule:line-length
          STACKS=$(find . -mindepth 1 -maxdepth 1 -type f -name "Pulumi.*.yaml" -printf "%f\n" | cut -d. -f2 | jq -R -s -c 'split("\n")[:-1]')
          echo "${STACKS}" | jq .
          echo "STACK_MATRIX=${STACKS}" >> "$GITHUB_OUTPUT"

    outputs:
      stack_matrix: ${{ steps.generate_matrix.outputs.STACK_MATRIX }}

  ##################################################
  # Deploy Pulumi Stack to GitHub Environment
  ##################################################

  pulumi:
    name: Pulumi Stack ${{ matrix.stack }}

    environment: ${{ matrix.stack }}

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30

    needs: matrix

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        stack: ${{ fromJson(needs.matrix.outputs.stack_matrix) }}

    steps:
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
          submodules: recursive
          fetch-depth: 1

      - id: install_nix
        name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          enable_kvm: true

      - id: cachix
        name: "Enable Cachix ❄️"
        uses: cachix/cachix-action@v15
        if: vars.CACHIX_CACHE_NAME != ''
        with:
          name: ${{ vars.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          useDaemon: true
          skipPush: false

      - id: cache
        name: Magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - id: devenv_install
        name: Devenv install
        run: |
          nix profile install --accept-flake-config nixpkgs#devenv

      - id: go_mod_download
        name: Go mod download
        shell: devenv shell --quiet bash -- -e {0}
        run: |
          go mod download

      - id: pulumi_login
        name: Pulumi login
        shell: devenv shell --quiet bash -- -e {0}
        env:
          PULUMI_ROOT: ${{ env.PULUMI_ROOT }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login

      - id: pulumi_preview
        name: Pulumi preview
        if: github.event.workflow_run.event == 'pull_request' || github.event.workflow_run.event == 'push'
        env:
          PULUMI_ROOT: ${{ env.PULUMI_ROOT }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        shell: devenv shell --quiet bash -- -e {0}
        run: >
          pulumi
          preview
          --refresh
          --show-replacement-steps
          --logtostderr
          --verbose=3
          --stack ${{ matrix.stack }}
          --color never
          > /tmp/pulumi-preview.txt

      - id: pulumi_preview_output
        name: Pulumi preview output
        if: github.event.workflow_run.event == 'pull_request' || github.event.workflow_run.event == 'push'
        shell: devenv shell --quiet bash -- -e {0}
        run: |
          # Capture the length of the plan output
          PLAN_LENGTH=$(wc -c < /tmp/pulumi-preview.txt)

          # Convert plan output to a format safe for GitHub Actions
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "plan<<$EOF" >> "$GITHUB_OUTPUT"
          if [ $PLAN_LENGTH -gt 64000 ];
          then
            echo "Plan output too long. Please check the workflow logs for the complete plan." >> "$GITHUB_OUTPUT"
            # Show the plan output in the workflow logs.
            cat /tmp/pulumi-preview.txt
          else
            # Show the plan output in the PR comment.
            cat /tmp/pulumi-preview.txt >> "$GITHUB_OUTPUT"
          fi
          echo "$EOF" >> "$GITHUB_OUTPUT"

      - id: get_pr_number
        name: Get PR Number
        if: always() && github.event.workflow_run.event == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const head_sha = context.payload.workflow_run.head_sha;
            console.log("Finding PR for SHA:", head_sha);

            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });

            const pr = prs.find(pr => pr.head.sha === head_sha);
            if (pr) {
              console.log("Found PR:", pr.number);
              core.setOutput('pr_number', pr.number);
            } else {
              core.setFailed("PR not found");
            }

      - id: pulumi_pr_comment_check
        name: Check for Pull Request comment
        if: always() && github.event.workflow_run.event == 'pull_request' && steps.get_pr_number.outputs.pr_number != ''
        shell: devenv shell --quiet bash -- -e {0}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.get_pr_number.outputs.pr_number }}
        run: |
          commentId=$(gh api \
            repos/${{ github.repository }}/issues/${PR_NUMBER}/comments \
            --jq '
              [.[] | select(.user.type=="Bot" and (.body | test("## Stack: `${{ matrix.stack }}`")))]
              | sort_by(.created_at)
              | reverse
              | .[0].id
            ' \
            || echo "")
          echo "Found comment ID: ${commentId:-none}"
          echo "comment_id=${commentId}" >> "$GITHUB_OUTPUT"

      - id: pulumi_pr_comment
        name: Comment on Pull Request
        uses: actions/github-script@v7
        if: always() && github.event.workflow_run.event == 'pull_request'
        with:
          script: |
            const commentId = '${{ steps.pulumi_pr_comment_check.outputs.comment_id }}' || null;
            const body = `
            ## Stack: \`${{ matrix.stack }}\`

            ### Status Summary

            #### Preview 🖌 \`${{ steps.pulumi_preview.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`hcl
            ${{ steps.pulumi_preview_output.outputs.preview }}
            \`\`\`

            </details>

            ### Info

            * **Pusher:** @${{ github.actor }}
            * **Trigger:** \`${{ github.event_name }}\`
            * **Workflow:** \`${{ github.workflow }}\`
            * **Directory:** \`${{ env.PULUMI_ROOT }}\`
            `;

            if (commentId) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: commentId,
                body: body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }

      - id: pulumi_update
        name: Pulumi update
        if: github.event.workflow_run.event == 'push' && steps.pulumi_preview.outcome == 'success'
        env:
          PULUMI_ROOT: ${{ env.PULUMI_ROOT }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        shell: devenv shell --quiet bash -- -e {0}
        run: >
          pulumi
          update
          --refresh
          --skip-preview
          --show-replacement-steps
          --logtostderr
          --verbose=3
          --yes
          --stack ${{ matrix.stack }}
